export const SUPPORTED_LANGUAGES = [
  { code: 'af', name: 'Afrikaans', rtl: false },
  { code: 'am', name: 'Amharic', rtl: false },
  { code: 'ar', name: 'Arabic', rtl: true },
  { code: 'as', name: 'Assamese', rtl: false },
  { code: 'az', name: 'Azerbaijani', rtl: false },
  { code: 'ba', name: 'Bashkir', rtl: false },
  { code: 'be', name: 'Belarusian', rtl: false },
  { code: 'bg', name: 'Bulgarian', rtl: false },
  { code: 'bn', name: 'Bengali', rtl: false },
  { code: 'bo', name: 'Tibetan', rtl: false },
  { code: 'br', name: 'Breton', rtl: false },
  { code: 'bs', name: 'Bosnian', rtl: false },
  { code: 'ca', name: 'Catalan', rtl: false },
  { code: 'cs', name: 'Czech', rtl: false },
  { code: 'cy', name: 'Welsh', rtl: false },
  { code: 'da', name: 'Danish', rtl: false },
  { code: 'de', name: 'German', rtl: false },
  { code: 'el', name: 'Greek', rtl: false },
  { code: 'en', name: 'English', rtl: false },
  { code: 'es', name: 'Spanish', rtl: false },
  { code: 'et', name: 'Estonian', rtl: false },
  { code: 'eu', name: 'Basque', rtl: false },
  { code: 'fi', name: 'Finnish', rtl: false },
  { code: 'fo', name: 'Faroese', rtl: false },
  { code: 'fr', name: 'French', rtl: false },
  { code: 'ga', name: 'Irish', rtl: false },
  { code: 'gl', name: 'Galician', rtl: false },
  { code: 'gu', name: 'Gujarati', rtl: false },
  { code: 'ha', name: 'Hausa', rtl: false },
  { code: 'he', name: 'Hebrew', rtl: true },
  { code: 'hi', name: 'Hindi', rtl: false },
  { code: 'hr', name: 'Croatian', rtl: false },
  { code: 'ht', name: 'Haitian', rtl: false },
  { code: 'hu', name: 'Hungarian', rtl: false },
  { code: 'hy', name: 'Armenian', rtl: false },
  { code: 'id', name: 'Indonesian', rtl: false },
  { code: 'is', name: 'Icelandic', rtl: false },
  { code: 'it', name: 'Italian', rtl: false },
  // { code: 'ja', name: 'Japanese', rtl: false },
  { code: 'jw', name: 'Javanese', rtl: false },
  { code: 'ka', name: 'Georgian', rtl: false },
  { code: 'kk', name: 'Kazakh', rtl: false },
  { code: 'km', name: 'Khmer', rtl: false },
  { code: 'ko', name: 'Korean', rtl: false },
  { code: 'la', name: 'Latin', rtl: false },
  { code: 'lb', name: 'Luxembourgish', rtl: false },
  { code: 'ln', name: 'Lingala', rtl: false },
  { code: 'lo', name: 'Lao', rtl: false },
  { code: 'lt', name: 'Lithuanian', rtl: false },
  { code: 'lv', name: 'Latvian', rtl: false },
  { code: 'mg', name: 'Malagasy', rtl: false },
  { code: 'mi', name: 'Maori', rtl: false },
  { code: 'mk', name: 'Macedonian', rtl: false },
  { code: 'ml', name: 'Malayalam', rtl: false },
  { code: 'mn', name: 'Mongolian', rtl: false },
  { code: 'mr', name: 'Marathi', rtl: false },
  { code: 'ms', name: 'Malay', rtl: false },
  { code: 'mt', name: 'Maltese', rtl: false },
  { code: 'my', name: 'Burmese', rtl: false },
  { code: 'ne', name: 'Nepali', rtl: false },
  { code: 'nl', name: 'Dutch', rtl: false },
  { code: 'nn', name: 'Norwegian', rtl: false },
  { code: 'no', name: 'Norwegian', rtl: false },
  { code: 'oc', name: 'Occitan', rtl: false },
  { code: 'pa', name: 'Punjabi', rtl: false },
  { code: 'pl', name: 'Polish', rtl: false },
  { code: 'ps', name: 'Pashto', rtl: true },
  { code: 'pt', name: 'Portuguese', rtl: false },
  { code: 'ro', name: 'Romanian', rtl: false },
  { code: 'ru', name: 'Russian', rtl: false },
  { code: 'sa', name: 'Sanskrit', rtl: false },
  { code: 'sd', name: 'Sindhi', rtl: true },
  { code: 'si', name: 'Sinhala', rtl: false },
  { code: 'sk', name: 'Slovak', rtl: false },
  { code: 'sl', name: 'Slovenian', rtl: false },
  { code: 'sn', name: 'Shona', rtl: false },
  { code: 'so', name: 'Somali', rtl: false },
  { code: 'sq', name: 'Albanian', rtl: false },
  { code: 'sr', name: 'Serbian', rtl: false },
  { code: 'su', name: 'Sundanese', rtl: false },
  { code: 'sv', name: 'Swedish', rtl: false },
  { code: 'sw', name: 'Swahili', rtl: false },
  { code: 'ta', name: 'Tamil', rtl: false },
  { code: 'te', name: 'Telugu', rtl: false },
  { code: 'tg', name: 'Tajik', rtl: false },
  { code: 'th', name: 'Thai', rtl: false },
  { code: 'tl', name: 'Tagalog', rtl: false },
  { code: 'tr', name: 'Turkish', rtl: false },
  { code: 'tt', name: 'Tatar', rtl: false },
  { code: 'uk', name: 'Ukrainian', rtl: false },
  { code: 'ur', name: 'Urdu', rtl: true },
  { code: 'uz', name: 'Uzbek', rtl: false },
  { code: 'vi', name: 'Vietnamese', rtl: false },
  { code: 'yi', name: 'Yiddish', rtl: true },
  { code: 'yo', name: 'Yoruba', rtl: false },
  { code: 'zh', name: 'Chinese', rtl: false }
] as const

const LANDSCAPE_FONT_SIZES = [
  { value: '22', label: 'Extra Small' },
  { value: '28', label: 'Small (Default)' },
  { value: '36', label: 'Medium' },
  { value: '44', label: 'Large' }
] as const

const PORTRAIT_FONT_SIZES = [
  { value: '12', label: 'Extra Small' },
  { value: '14', label: 'Small (Default)' },
  { value: '18', label: 'Medium' },
  { value: '20', label: 'Large' }
] as const

export const getFontSizes = (isPortrait: boolean) => 
  isPortrait ? PORTRAIT_FONT_SIZES : LANDSCAPE_FONT_SIZES

export const getDefaultFontSize = (isPortrait: boolean) =>
  isPortrait ? '14' : '28'

export type FontSize = typeof LANDSCAPE_FONT_SIZES[number]['value'] | typeof PORTRAIT_FONT_SIZES[number]['value']

export type LanguageCode = typeof SUPPORTED_LANGUAGES[number]['code']